# GitHub Sponsors configuration
# This file can be used when the project decides to accept donations/sponsorships

# github: [DARIO-engineer]  # Uncomment when GitHub Sponsors is set up

# Other platforms can be added as needed:
# patreon: username
# open_collective: verse-musa
# ko_fi: username
# custom: ['https://www.example.com']

# Note: This is a community project and currently does not accept monetary donations.
# The best way to support is by contributing code, documentation, or sharing the project!
